# This workflow is disabled to avoid Docker Hub authentication issues
# Only using GitHub Container Registry (ghcr.io) via docker-build.yml

name: Docker Hub Build (Disabled)

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
    - name: Info
      run: |
        echo "Docker Hub workflow is disabled"
        echo "Using GitHub Container Registry instead via docker-build.yml"
        echo "Images are available at: ghcr.io/${{ github.repository }}"